### ISSUE TITLE
GoogleSignInButton doesn't redirect to loggedIn page set in Login widget

### ISSUE THREAD

**Issue by andrei-cristea-EW** [ctjl96/login#1]
Maybe I'm doing something wrong, but the button successfully logs in to Firebase with my Google account, but what it fails to do is to navigate to the page set in the "loggedIn" property.
The Login widget is found in main.dart. The GoogleSignInButton is found in welcome_page.dart.
I attached both, but renamed them to ".txt", because GitHub doesn't allow .dart upload:
[welcome_page.txt](https://github.com/christiantjl/login/files/4589404/welcome_page.txt)
[main.txt](https://github.com/christiantjl/login/files/4589405/main.txt)

**Comment by ctjlewis** [comment]
@crivatz11 I actually used this for a personal project and have not been maintaining the package, it's likely a bug and not your fault.  Can you reproduce this in a Codepen or Dartpad project just so I don't have to do the work of setting up a test?  TYVM.

Also, have you made sure that you set up Firebase for your project by adding the Google Services JSON file etc.? https://firebase.google.com/docs/flutter/setup

Please also review the debugging steps at the bottom of the README if you can.

**Comment by ctjlewis** [comment]
@crivatz11 Any updates?

**Comment by andrei-cristea-EW** [comment]
Hey, sorry, just saw your reply.
I ended up not using the package anymore because of this issue and because I needed to manually do Facebook login too.
I don't think I still have the code anymore, I'll check my commits and try to put something up.

**Comment by andrei-cristea-EW** [comment]
But thanks for the reply!

**Comment by ctjlewis** [comment]
No worries, very sorry about that.
